const dailyEvents = [
  {
    date: "2022-07-01",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-02",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [
      {
        firstName: "David",
        lastName: "Davis",
      },
      {
        firstName: "Dylan",
        lastName: "Su",
      },
    ],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-03",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [
      {
        firstName: "David",
        lastName: "Davis",
      },
    ],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-04",
    companyHoliday: ["Independence Day"],
    bankHoliday: true,
    anniversaryMembers: [],
    birthdayMembers: [
      {
        firstName: "Julie",
        lastName: "West",
      },
      {
        firstName: "Nicholas",
        lastName: "Bryant",
      },
      {
        firstName: "Kelly",
        lastName: "Garcia",
      },
    ],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-05",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [
      {
        invoiceDate: "2022-07-01",
      },
      {
        invoiceDate: "2022-07-01",
      },
    ],
    payday: null,
  },
  {
    date: "2022-07-06",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [
      {
        firstName: "Julie",
        lastName: "West",
      },
      {
        firstName: "Nicholas",
        lastName: "Bryant",
      },
      {
        firstName: "Kelly",
        lastName: "Garcia",
      },
    ],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-07",
    companyHoliday: [],
    bankHoliday: true,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-08",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-09",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-10",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-11",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-12",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-13",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-14",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-15",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-16",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-17",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-18",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-19",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-20",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-21",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-22",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-23",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-24",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-25",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-26",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-27",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-28",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-29",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-30",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
  {
    date: "2022-07-31",
    companyHoliday: [],
    bankHoliday: false,
    anniversaryMembers: [],
    birthdayMembers: [],
    firstDayMembers: [],
    invoices: [],
    payday: null,
  },
];

export default dailyEvents;
